#!/bin/bash
echo "🎲 Gambino Coin System Information"
echo "=================================="
echo "🌐 Frontend URL: http://$(hostname -I | awk '{print $1}'):3000"
echo "🔧 Backend API: http://$(hostname -I | awk '{print $1}'):3001/health"
echo "📊 Admin Panel: http://$(hostname -I | awk '{print $1}'):3001/api/admin/stats"
echo ""
echo "🔐 MongoDB Credentials:"
echo "Username: gambinouser"
echo "Password: jhI+PDopCbhL/uAwniiKU2DSQX6Rv8LEXR5smWQZfIU="
echo ""
echo "📝 Useful Commands:"
echo "- Check status: pm2 status"
echo "- View logs: pm2 logs"
echo "- Restart all: pm2 restart all"
echo "- Check containers: docker-compose ps"
echo "- Health check: curl localhost:3001/health"
